version: "3.8"

volumes:
  postgresql-mlflow-data:
  mlflow-artifact-store:
    

x-app-template: &app-template
  user: "${USER_ID:-1000}"
  hostname: "${HOST_NAME:-Man City DS Projects}"
  image: mancity-ds-project
  platform: linux/amd64
  container_name: MANCITY-container
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    args:
      USER_NAME: "${USER_NAME:-yxing}"
      USER_ID: "${USER_ID:-1000}"
  env_file:
    - .envs/.mlflow-common
    - .envs/.mlflow-dev
    - .envs/.postgres
  volumes:
    - ./:/app/
    - mlflow-artifact-store:/mlflow-artifact-store
    - ~/.config/gcloud/:/home/${USER_NAME:-yxing}/.config/gcloud
  ipc: host
  init: true


services: 
  mlflow-db:
    container_name: MANCITY-mlflow-backend-store
    image: postgres:14
    env_file:
      - .envs/.mlflow-common
      - .envs/.mlflow-dev
      - .envs/.postgres
    ports:
      - 5433:5432
    profiles:
      - dev
  
  app-dev:
    <<: *app-template
    container_name: MANCITY-dev-container
    ports:
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - dev  

  app-prod:
    <<: *app-template
    container_name: MANCITY-prod-container
    env_file:
      - .envs/.mlflow-common
      - .envs/.mlflow-prod
    ports:
      - ${PROD_MLFLOW_SERVER_PORT}:${PROD_MLFLOW_SERVER_PORT}
    profiles:
      - prod

  app-ci:
    <<: *app-template
    container_name: MANCITY-ci-container
    ports:
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    profiles:
      - ci


